### ISSUE TITLE
more movie/game/book references in the communicator

### ISSUE THREAD

**Issue by wstoettinger** [FortAwesome/spaceawesome-feedback#5]
it's fun to stumble upon one or the other movie reference in the communicator. however, I tried many and there is a lot of potential. 
back to the future, 1984, strange new world, the planet of the apes ... you get my point.

would be great to have a couple more Easter eggs in there 👍🏻

**Comment by ej2** [comment]
There are already some Back to the Future references in the game.  I will look into adding some for Planet of the Apes and Strange New World. Thanks for the feedback!
